### ISSUE TITLE
Provide Payload Examples

### ISSUE THREAD

**Issue by ciss84** [a0zhar/PS4-Payload-SDK#1]
hello this possibel help for use function is_fw_spoofed ??? and camera exempel ???

**Comment by ciss84** [comment]
payload exemple pls

**Comment by a0zhar** [comment]
Of course, do you want it via Discord, or should I make an "example" directory here and place them there?

**Comment by a0zhar** [comment]
> payload exemple pls

### Here's an example of how to use `is_fw_spoofed()`
```C
if (is_fw_spoofed()) { 
    sendNotification(0, "The PS4 Firmware is Spoofed!!!");
} else {
    sendNotification(0, "The PS4 Firmware is not Spoofed!");
}
```
### What do you need help with, regarding the camera part?

**Comment by ciss84** [comment]
just this thx ??
 for camera add temp cpu and sock in screan

**Comment by ciss84** [comment]
this my spoof  !! spoof_fw(SPOOF2);
 im includ same this ??  

if (is_fw_spoofed()) { 
    spoof_fw(SPOOF2);
    printf_debug(0, "The PS4 Firmware is Spoofed!!!");
  } else {
    printf_debug(0, "The PS4 Firmware is not Spoofed!");
}

**Comment by a0zhar** [comment]
> this my spoof !! spoof_fw(SPOOF2); im includ same this ?? 
> if (is_fw_spoofed()) { spoof_fw(SPOOF2); printf_debug(0, "The PS4 Firmware is Spoofed!!!"); } else { printf_debug(0, "The PS4 Firmware is not Spoofed!"); }

# The `is_fw_spoofed()` function checks if the ps4 firmware has been spoofed before running this payload


###  `spoof_fw` is not included in the SDK, but I assume it spoofs the fw to the value of  `SPOOF2` <br>
###  The `printf_debug` will send the msg to a socket server, running on the IP and PORT that u defined 
```C
if (is_fw_spoofed()) {
spoof_fw(SPOOF2);//spoof the firmware if it has already been spoofed 
printf_debug(0, "The PS4 Firmware is Spoofed!!!");
} else {
printf_debug(0, "The PS4 Firmware is not Spoofed!");
}
```

**Comment by a0zhar** [comment]
This is how u use  camera i guess

```C
#include "ps4.h"
int _main(void) {
  initKernel();
  initLibc();
  initNetwork();
  initCamera();


  printf_debug("debugnet Initialized\n");

  int handle;
  int ret;
  int count;
  int index;
  int modules[256];

  //First we check if camera is attached it must return 1 if not we can't follow and return
  ret = sceCameraIsAttached(0);
  if (!ret) {

    printf_debug("received error %08x\n", ret);
    return ret;

  }
  //there is a check in libSceCamera.sprx it seems 0x0FF is the userid for service camera
  handle = sceCameraOpen(0x0FF, 0, 0, NULL);
  if (handle < 0) {
    printf_debug("sceCameraOpen received error: %08x\n", handle);
    return handle;
  }
  printf_debug("Camera opened with handle: %d\n", handle);
  //function check size and some values on unknown1 and unknown2 test and error you will get 802e0000 on bad values
  SceCameraStartParameter param;
  param.size = 0x18;
  param.unknown1 = 0x08;
  param.unknown2 = 0x08;

  ret = sceCameraStart(handle, &param);
  if (ret < 0) {
    printf_debug("sceCameraStart received error %08x\n", ret);
    printf_debug("Stop camera return %08x\n", sceCameraStop(handle));
    printf_debug("Closing camera return %08x\n", sceCameraClose(handle));
    return ret;
  }
  printf_debug("Camera started led is on :P\n");
  //function check size it must be < 0x209 and correct values on unknown1. bad values or incorrect size and you will get get 0x802e0000
  SceCameraFrameData frame;
  frame.size = 0x208;
  frame.unknown1 = 0;
  for (index = 0; index < 10; index++) {
    ret = sceCameraGetFrameData(handle, &frame);
    if (ret < 0) {
      printf_debug("Frame %d sceCameraGetFrameData received error %08x\n", index, ret);

    } else {
      printf_debug("Frame %d sceCameraGetFrameData return  %d fine we got a frame\n", index, ret);
    }
  }
  ret = sceCameraStop(handle);
  if (ret < 0) {
    printf_debug("received error %08x\n", ret);

  }
  printf_debug("Camera stop led off\n");

  sceCameraClose(handle);
  return 0;
}

```
ref:https://raw.githubusercontent.com/o1line/ps4-payload-sdk/master/examples/camera/source/main.c

**Comment by a0zhar** [comment]
> for camera add temp cpu and sock in screan

What do you mean??
Like add TEMP, CPU usage and Socket As overlay on camera ? or what do u mean bro.

**Comment by ciss84** [comment]
spoof_fw this my fonction have includ in sdk  !! for temp have add notifi you have idéa for includ in screan game ???

**Comment by a0zhar** [comment]
> spoof_fw this my fonction have includ in sdk !! for temp have add notifi you have idéa for includ in screan game ???

Qu'est-ce que tu veux dire, mon frère ? Vous pouvez taper en français, c'est bon.

**Comment by ciss84** [comment]
ok merci !! spoof_fw j'ai inclu la fonction dans le sdk pour un spoof 9.50 et je veux faire fonctionée la detection du spoof pour pouvoir utilisé la toolbox avec mon hen !!!

**Comment by ciss84** [comment]
pour la temperature du cpu et du sock j'ai une fonction avec notifiquation j'aimeré l'inclure come avec la toolbox sur l'ecrand de jeux

**Comment by ciss84** [comment]
si tu peut m'aidé sa serai cool

**Comment by ciss84** [comment]
https://t.me/SonGoKu84Ciss  mon telegram si tu et dispo demain sa sera plus simple

**Comment by ciss84** [comment]
bonne nuit frere merci

**Comment by a0zhar** [comment]
Pouvez-vous s'il vous plaît préciser ce que vous voulez dire, mon frère ? Que voulez-vous dire par la température de la chaussette ? Et quelle boîte à outils voulez-vous dire ? Avez-vous créé la vôtre ?

**Comment by ciss84** [comment]
temperature du cpu et de la carte mere  !! orbistoolbox part osm

**Comment by a0zhar** [comment]
Oh, je comprends maintenant. Parlons-en demain. Bonne nuit, mon frère ; je ferai de mon mieux pour vous aider.

**Comment by ciss84** [comment]
jutilise sa pour avoir la temperature de la ps4

  while (temperature) {
  uint32_t CPU_Temp;
  uint32_t SOC_Temp;
  uint32_t ret = sceKernelGetCpuTemperature(&CPU_Temp);
  uint32_t retb = sceKernelGetSocSensorTemperature(0, &SOC_Temp);
  sceKernelSleep(100);
  printf_debug("returned %d\n%i", ret, retb);
  printf_notification3("Temperature\n*Cpu: %d*C\n*Soc: %i*C", CPU_Temp, SOC_Temp);
}

**Comment by ciss84** [comment]
merci une bonne nuit frerot
